set nocompatible
set number
set relativenumber
set tabstop=4
set shiftwidth=4
set smartindent
set incsearch
set ignorecase
set smartcase
set nowrap
set wildmenu
set backspace=indent,eol,start
set laststatus=2
set ruler
set noerrorbells
set scrolloff=20
set mouse=a
set clipboard=unnamed
autocmd FileType python,yaml setlocal expandtab
syntax on
set termguicolors
set background=light
colorscheme catppuccin_latte

set guicursor=a:blinkwait0-blinkon0-blinkoff0
set guifont=Iosevka:h14
